[package]
name = "mock-c8y"
version = "0.1.0"
authors = ["Tej Babu Balireddi <tejbabu91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"rocket" = "0.4"
